DROP TABLE TICKETS_LABELS;
DROP CONSTRAINT FK_LABEL_HAS_TICKETS;
DROP CONSTRAINT FK_TICKET_HAS_LABELS;

DROP TABLE TICKETS;
DROP TABLE LABELS;

CREATE TABLE TICKETS(
   ID BIGINT PRIMARY KEY,
   TITLE VARCHAR(255) NOT NULL,
   PRIORITY INTEGER DEFAULT 0
);

CREATE TABLE LABELS(
    ID BIGINT PRIMARY KEY,
    TEXT CHAR(254) NOT NULL UNIQUE
);

CREATE TABLE TICKETS_LABELS(
    TICKET_ID BIGINT,
    LABEL_ID BIGINT,
    CONSTRAINT FK_LABEL_HAS_TICKETS
        FOREIGN KEY (TICKET_ID)
        REFERENCES TICKETS(ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_TICKET_HAS_LABELS
            FOREIGN KEY (LABEL_ID)
            REFERENCES LABELS(ID)
            ON DELETE CASCADE
);