DROP TABLE TICKETS;
CREATE TABLE TICKETS(
   ID BIGSERIAL PRIMARY KEY,
   TITLE VARCHAR(255) NOT NULL,
   PRIORITY INTEGER DEFAULT 0
);

DROP TABLE LABELS;
CREATE TABLE LABELS(
    TICKET_ID BIGINT,
    LABEL CHAR(255) NOT NULL
);

DROP TABLE USERS;
CREATE TABLE USERS(
    ID BIGSERIAL PRIMARY KEY,
    GOOGLE_ID VARCHAR(255),
    EMAIL VARCHAR(255),
    FULL_NAME VARCHAR(255),
    PICTURE VARCHAR(2048),
    LOCALE VARCHAR(16)
);
