DROP TABLE TICKETS;
CREATE TABLE TICKETS(
   ID BIGSERIAL PRIMARY KEY,
   TITLE VARCHAR(255) NOT NULL,
   PRIORITY INTEGER DEFAULT 0
);

DROP TABLE LABELS;
CREATE TABLE LABELS(
    TICKET_ID BIGINT,
    LABEL CHAR(255) NOT NULL
);
